export const BodyConfiguration = 'BodyConfiguration';
export const Age = 'Age';
export const Summary = 'summary';
export const Settings = 'settings';
export const Workout = 'workout';
export const Graphs = 'graphs';
export const BodyParameters = 'Body Parameters';
export const Weight = 'Weight';
export const Height = 'Height';